---
abstract: 'Display information about POE sessions and events'
author:
  - 'Sebastien Aperghis-Tramoni <sebastien@aperghis.net>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Devel-Top
provides:
  POE::Devel::Top:
    file: lib/POE/Devel/Top.pm
    version: 0.001
requires:
  POE: 0
  POE::API::Peek: 0
  Term::ANSIColor: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.001
